version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
        HTTP_PORT: 8000
        HITBTC_HOST: "api.hitbtc.com"
        HITBTC_CHANNEL: "/api/2/ws"
        SYMBOLS: BTCUSD|ETHBTC|XMRTUSD|BCNBTC
